---
# yaml-language-server: $schema=https://json.schemastore.org/semantic-release.json
branches:
  - main

plugins:
  - "@semantic-release/github"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      releaseRules:
        - type: docs
          release: patch
        - type: refactor
          release: patch
        - type: style
          release: patch
        - type: patch
          release: patch
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
