---
branches:
  - main

plugins:
  - "@semantic-release/github"
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
