---
# =================================================================================================
# Areas
# =================================================================================================
- name: area/devcontainer
  color: "0000FF"
  description: Changes made to the DevContainer configuration

- name: area/github
  color: "000000"
  description: Changes made to the GitHub configuration

- name: area/container
  color: "3970E4"
  description: Changes made to the Docker configuration

- name: area/renovate
  color: "027fa0"
  description: Changes made to the Renovate configuration

- name: area/semantic-release
  color: "f6412d"
  description: Changes made to the Semantic configuration

- name: area/scripts
  color: "212121"
  description: Changes made to any script

- name: area/docs
  color: "9e59ff"
  description: Changes made to the documentation

# =================================================================================================
# Renovate Types
# =================================================================================================
- name: renovate/github-action
  color: "000000"

- name: renovate/container
  color: "3970E4"

# =================================================================================================
# Semantic Types
# =================================================================================================
- name: type/digest
  color: "ffeC19"
- name: type/patch
  color: "ffeC19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"

# =================================================================================================
# Size Types
# =================================================================================================
- name: size/XS
  color: "0000ff"
- name: size/S
  color: "000ff0"
- name: size/M
  color: "00ff00"
- name: size/L
  color: "0ff000"
- name: size/XL
  color: "ff0000"
- name: size/XXL
  color: "ff00ff"
