---
area/devcontainer:
  - changed-files:
      - any-glob-to-any-file: ".devcontainer/**"

area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
      - any-glob-to-any-file: ".gitignore"
      - any-glob-to-any-file: ".gitattributes"
      - any-glob-to-any-file: ".editorconfig"

area/container:
  - changed-files:
      - any-glob-to-any-file: "**/*Dockerfile*"
      - any-glob-to-any-file: "**/.dockerignore"
      - any-glob-to-any-file: "**/*docker-compose.*"
      - any-glob-to-any-file: "**/*compose.*"

area/renovate:
  - changed-files:
      - any-glob-to-any-file: "renovate.json5"
      - any-glob-to-any-file: ".github/config/renovate/**"
      - any-glob-to-any-file: ".renovate/**"
      - any-glob-to-any-file: ".config/renovate/**"

area/semantic-release:
  - changed-files:
      - any-glob-to-any-file: ".releaserc.*"

area/scripts:
  - changed-files:
      - any-glob-to-any-file: "scripts/**"
      - any-glob-to-any-file: ".scripts/**"
      - any-glob-to-any-file: ".github/scripts/**"

area/docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**"
      - any-glob-to-any-file: "*.md"
      - any-glob-to-any-file: "LICENSE"
