---
name: Docker Release

on:
  workflow_call:
    inputs:
      image-name:
        type: string
        description: The name of the image to build.
        default: ""
        required: false
      platforms:
        type: string
        description: The OS arches for which to build the docker image.
        default: linux/amd64
        required: false
      custom-tag:
        type: string
        description: Additional custom tags for the image.
        required: false
      context:
        type: string
        description: The context for the docker build command.
        required: false
      dockerfile:
        type: string
        description: The path to the dockerfile to build.
        required: false
      build-args:
        type: string
        description: Additional build args to pass to the build command.
        default: ""
        required: false

env:
  IMAGE_NAME: "${{ inputs.image-name || 'ghcr.io/${{ github.repository }}' }}"
  DOCKERFILE: "${{ inputs.dockerfile || './Dockerfile' }}"
  BUILD_CONTEXT: "${{ inputs.context || '.' }}"
  BUILD_PLATFORMS: "${{ inputs.platforms || 'linux/amd64' }}"
  BUILD_ARGS: "${{ inputs.build-args || '' }}"

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_RW_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: "${{ env.IMAGE_NAME }}"
          tags: |
            type=ref,event=tag
            type=ref,event=pr
            type=sha,prefix=sha-,format=short
            ${{ inputs.custom-tag }}

      - name: Build and Push
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
        with:
          context: "${{ env.BUILD_CONTEXT }}"
          file: "${{ env.DOCKERFILE }}"
          platforms: "${{ env.BUILD_PLATFORMS }}"
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
          build-args: "${{ env.BUILD_ARGS }}"
