---
name: Cleanup PR Images

on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: "Tag to delete"
        required: true
        default: ""
      dryRun:
        type: boolean
        description: Dry Run
        default: false
        required: true

jobs:
  purge-image:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          organization: ${{ github.repository_owner }}
          token: ${{ steps.app-token.outputs.token }}
          container: ${{ github.event.repository.name }}
          dry-run: ${{ inputs.dryRun }}
          prune-tags-regexes: |
            ${{ inputs.tag }}
          prune-untagged: false
          keep-last: 0
