---
name: Docker Delete Image Tag

on:
  workflow_call:
    inputs:
      image-name:
        type: string
        description: The name of the image to clean up.
        default: ""
        required: true
      image-tag:
        type: string
        description: The tag of the image to delete.
        default: false
        required: false
      dry-run:
        type: number
        description: Set the value to 0 to actually delete the package versions.
        default: 1
        required: false

jobs:
  docker-cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Delete Images
        uses: cresh-io/action-ghcr-batch-delete-versions@v1.2.1
        with:
          github-access-token: "${{ steps.app-token.outputs.token }}"
          org: "${{ github.repository_owner }}"
          package_name: ${{ inputs.image-name }}
          package_type: "container"
          selector: |
            type=name;operator=startsWith;value=${{ inputs.image-tag }}
          excluder: |
            type=name;operator=startsWith;value=v
          dry-run: ${{ github.event.inputs.dry-run }}
