---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Git Release SemVer

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry Run"
        default: true
        required: false
        type: boolean

  push:
    branches: ["main"]
    paths:
      - ".github/workflows/reusable-**"
      - ".renovate/*.json5"
      - ".releaserc.yaml"

  pull_request:
    paths:
      - ".github/workflows/git-release-semver.yaml"
      - ".github/workflows/reusable-**"

jobs:
  release:
    uses: ./.github/workflows/reusable-release-semver.yaml
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run || github.event_name == 'pull_request' }}
