---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Git: Release SemVer"

on:
  workflow_call:
    inputs:
      dry-run:
        type: boolean
        description: Dry Run
        default: false
        required: false
      branch:
        type: string
        description: The branch to release from.
        default: main
        required: false
      plugins:
        type: string
        description: The plugins to use with semantic-release.
        default: |
          @semantic-release/commit-analyzer
          @semantic-release/release-notes-generator
          @semantic-release/github
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@3378cda945da322a8db4b193e19d46352ebe2de5 # v1.10.4
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: "${{ inputs.dry-run }}"
          branch: "${{ inputs.branch }}"
          extra_plugins: "${{ inputs.plugins }}"
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
