---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  yamllint:
    uses: ./.github/workflows/reusable-yamllint.yaml
    secrets: inherit
    with:
      yamllint-args: "--config-file=.yamllint.yaml"

  actionlint:
    uses: ./.github/workflows/reusable-actionlint.yaml
    secrets: inherit
    with:
      actionlint-version: "v1.7.1"

  shellcheck:
    uses: ./.github/workflows/reusable-shellcheck.yaml
    secrets: inherit

  markdownlint:
    uses: ./.github/workflows/reusable-markdownlint.yaml
    secrets: inherit
    with:
      markdownlint-cli-version: "0.41.0"

  commitlint:
    uses: ./.github/workflows/reusable-commitlint.yaml
    secrets: inherit
    with:
      commitlint-version: "v19.5.0"
