---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  workflow_dispatch: {}

  pull_request:
    paths:
      - "*.yaml"

jobs:
  renovate:
    uses: ./.github/workflows/reusable-yamllint.yaml
    secrets: inherit
    with:
      yamllint-args: "--config-file=.yamllint.yaml"
