---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  workflow_dispatch: {}

  pull_request:
    paths:
      - "**.yaml"

jobs:
  yamllint:
    uses: ./.github/workflows/reusable-yamllint.yaml
    secrets: inherit
    with:
      yamllint-args: "--config-file=.yamllint.yaml"

  actionlint:
    uses: ./.github/workflows/reusable-actionlint.yaml
    secrets: inherit
    with:
      actionlint-version: "v1.7.1"
