---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  actionlint:
    uses: ./.github/workflows/reusable-actionlint.yaml
    with:
      config-file: .github/configs/actionlint.yaml

  commitlint:
    uses: ./.github/workflows/reusable-commitlint.yaml
    secrets: inherit
    with:
      config-file: ./.github/configs/commitlint.config.mjs

  markdownlint:
    uses: ./.github/workflows/reusable-markdownlint.yaml
    secrets: inherit
    with:
      config-file: .github/configs/.markdownlint.yaml

  shellcheck:
    uses: ./.github/workflows/reusable-shellcheck.yaml

  yamllint:
    uses: ./.github/workflows/reusable-yamllint.yaml
    with:
      config-file: .github/configs/.yamllint.yaml
