---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Semantic Release

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/reusable-**"
      - ".configs/**"
jobs:
  release:
    uses: ./.github/workflows/reusable-release-semver.yaml
    secrets: inherit
