---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Label Sync

on:
  workflow_dispatch:
    inputs:
      config-file:
        type: string
        description: Path to the labeler config file.
        default: .github/configs/labels.yaml

  workflow_call:
    inputs:
      config-file:
        type: string
        description: Path to the labeler config file.
        default: .github/configs/labels.yaml

  push:
    branches: [ "main" ]
    paths: [ ".github/configs/labels.yaml" ]

  schedule:
    - cron: "0 0 * * *" # Every day at midnight

env:
  LABEL_SYNC_CONFIG_FILE: "${{ inputs.config-file || '.github/configs/labeler.yaml' }}"

jobs:
  label-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: "${{ steps.app-token.outputs.token }}"
          sparse-checkout: .github/configs/labels.yaml

      - name: Sync Labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          token: "${{ steps.app-token.outputs.token }}"
          config-file: "${{ env.LABEL_SYNC_CONFIG_FILE }}"
          delete-other-labels: true
