---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Markdown Lint

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: The directory to lint.
        required: false
        default: "."
      config-file:
        required: false
        type: string
        default: ".markdownlint.yaml"
        description: The config file to use.
      extra-flags:
        required: false
        type: string
        default: ""
        description: Extra CLI flags.

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Tools
        uses: jdx/mise-action@v2.1.11
        with:
          mise_toml: |
            [tools]
            node = "latest"
            "npm:conventional-changelog-conventionalcommits" = "latest"
            "npm:markdownlint-cli" = "latest"

      - name: Run markdownlint
        working-directory: ${{ inputs.working-directory }}
        run:  |
          markdownlint **.md \
            --dot \
            --config ${{ inputs.config-file }} \
            ${{ inputs.extra-flags }}
