---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - CommitLint

on:
  workflow_call:
    inputs:
      config-file:
        description: "Path to the config file"
        type: string
        required: false
        default: ".commitlintrc.json"
      extra-flags:
        description: "Extra CLI flags"
        type: string
        required: false
        default: "--color --verbose"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    container: docker.io/library/node:23-bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Tools
        run: npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$PR_TITLE" > file.txt
          commitlint --edit=file.txt \
            --config=${{ inputs.config-file }} \
            ${{ inputs.extra-flags }}
