---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - ActionLint

on:
  workflow_call:
    inputs:
      go-version:
        description: "Go version"
        required: false
        type: string
        default: "stable"
      actionlint-version:
        description: "ActionLint version"
        required: false
        type: string
        default: "latest"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@${{ inputs.actionlint-version }}

      - name: Run actionlint
        run: actionlint
