---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Goreleaser

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        description: The Go version to use.
        required: false
        default: "stable"
      goreleaser-version:
        type: string
        description: The GoReleaser version to use.
        required: false
        default: "v2.7.0"
      dry-run:
        type: boolean
        description: Whether to run a dry run or not.
        default: false

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1.11.5
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Install goreleaser
        run: go install github.com/goreleaser/goreleaser/@${{ inputs.goreleaser-version }}

      - name: Login to Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GHCR_RW_TOKEN }}"

      - name: Run GoReleaser
        run: goreleaser release --clean ${{ inputs.dry-run && '--snapshot' || '' }}
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
          # FIXME: maybe figure out how to make this work with the github app token...
          TAP_GITHUB_TOKEN: "${{ secrets.GHCR_RW_TOKEN }}"
