---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Markdown Lint

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version"
        type: string
        required: false
        default: "latest"
      markdownlint-cli-version:
        description: "markdownlint-cli version"
        type: string
        required: false
        default: "latest"
      markdownlint-flags:
        description: "Extra flags to pass to markdownlint"
        type: string
        required: false
        default: ""

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "${{ inputs.node-version }}"

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli@${{ inputs.markdownlint-cli-version }}

      - name: Run markdownlint
        run: find . -name "*.md" -exec markdownlint ${{ inputs.markdownlint-flags }} {} +
