---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Markdown Lint

on:
  workflow_call:
    inputs:
      working-directory:
        description: "The directory to lint"
        type: string
        required: false
        default: "."
      config-file:
        description: "Path to the markdownlint config file"
        type: string
        required: false
        default: ".markdownlint.yaml"
      extra-flags:
        description: "Additional CLI flags for markdownlint"
        type: string
        required: false
        default: ""

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    container: docker.io/library/node:23-bookworm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install MarkdownLint
        run: |
          npm install markdownlint-cli
          npm list --depth=0

      - name: Run MarkdownLint
        working-directory: ${{ inputs.working-directory }}
        run: |
          markdownlint "**/*.md" --dot --config ${{ inputs.config-file }} ${{ inputs.extra-flags }}
