---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Go Test

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        description: The Go version to use.
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Run Tests
        run: go test -v ./... -race -covermode=atomic
