---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - GolangCI Lint

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: The directory to lint.
        required: false
        default: "."
      extra-flags:
        required: false
        type: string
        default: ""
        description: Extra CLI flags.

jobs:
  lint:
    runs-on: ubuntu-latest
    container: docker.io/library/golang:1.24.0-bookworm

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install GolangCI Lint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@latest

      - name: Setup Tools
        uses: jdx/mise-action@v2.1.11
        with:
          mise_toml: |
            [tool]
            "aqua:golangci/golangci-lint" = "latest"

      - name: Run golangci-lint
        working-directory: ${{ inputs.working-directory }}
        run: golangci-lint run ${{ inputs.extra-flags }}
