---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - GolangCI Lint

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        description: The Go version to use.
        required: false
        default: "stable"
      golangci-version:
        type: string
        description: The version of golangci-lint to use.
        required: false
        default: "v1.60" #TODO add renovate annotation
      golangci-args:
        type: string
        description: Additional arguments to pass to golangci
        required: false
        default: ""

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@3378cda945da322a8db4b193e19d46352ebe2de5 # v1.10.4
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6.1.0
        with:
          version: "${{ inputs.golangci-version }}"
          args: "${{ inputs.golangci-args }}"
