---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - CommitLint

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version"
        required: false
        type: string
        default: "latest"
      commitlint-version:
        description: "Commitlint version"
        required: false
        type: string
        default: "latest"
      commitlint-flags:
        description: "Extra CLI flags to pass to commitlint."
        required: false
        type: string
        default: ""

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "${{ inputs.node-version }}"

      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install -g @commitlint/cli@${{ inputs.commitlint-version }}

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$PR_TITLE" > file.txt
          commitlint ${{ inputs/commitlint-flags }} --verbose --color -e=file.txt
