---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - GolangCI Lint

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        description: The Go version to use.
        required: false
        default: "stable"
      golangci-version:
        type: string
        description: The version of golangci-lint to use.
        required: false
        default: "v1.63.4" # TODO add renovate annotation
      golangci-args:
        type: string
        description: Additional arguments to pass to golangci
        required: false
        default: ""

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@${{ inputs.golangci-version }}

      - name: Run golangci-lint
        run: golangci-lint run ${{ inputs.golangci-args }}
