---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Release SemVer

on:
  workflow_call:
    inputs:
      dry-run:
        type: boolean
        description: Dry Run
        default: false
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: "${{ inputs.dry-run }}"
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
