---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - YAMLLint

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: The directory to lint.
        required: false
        default: "."
      config-file:
        required: false
        type: string
        default: ".yamllint.yaml"
        description: The yamllint config file to use.
      extra-flags:
        required: false
        type: string
        default: ""
        description: Extra CLI flags.

jobs:
  lint:
    runs-on: ubuntu-latest
    container: docker.io/library/python:3.12-bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        working-directory: ${{ inputs.working-directory }}
        run: yamllint --config-file ${{ inputs.config-file }} ${{ inputs.extra-flags }} .
