---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Release SemVer

on:
  workflow_call:
    inputs:
      dry-run:
        type: boolean
        description: Dry Run
        default: false
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: "${{ inputs.dry-run }}"
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
