---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Goreleaser

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        description: The Go version to use.
        required: false
        default: "stable"
      goreleaser-version:
        type: string
        description: The GoReleaser version to use.
        required: false
        default: "~> v2"
      dry-run:
        type: boolean
        description: Whether to run a dry run or not.
        default: false

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@136412a57a7081aa63c935a2cc2918f76c34f514 # v1.11.2
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Login to Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GHCR_RW_TOKEN }}"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          distribution: goreleaser
          version: "${{ inputs.goreleaser-version }}"
          args: release --clean ${{ inputs.dry-run && '--snapshot' || '' }}
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
          TAP_GITHUB_TOKEN: "${{ secrets.GHCR_RW_TOKEN }}" # FIXME: maybe figure out how to make this work with the github app token...
