---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - ActionLint

on:
  workflow_call:
    inputs:
      config-file:
        required: false
        type: string
        default: "actionlint.yaml"
        description: Path to the config file.
      extra-flags:
        required: false
        type: string
        default: ""
        description: Extra CLI flags.

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Tools
        uses: jdx/mise-action@v2.1.11
        with:
          mise_toml: |
            [tools]
            "aqua:rhysd/actionlint" = "latest"

      - name: Run actionlint
        run: actionlint -config-file ${{ inputs.config-file }} ${{ inputs.extra-flags }}
