---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Release SemVer

on:
  workflow_call:
    inputs:
      dry-run:
        type: boolean
        description: Dry Run
        default: false
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1.11.5
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Setup Tools
        uses: jdx/mise-action@v2.1.11
        with:
          version: latest
          mise_toml: |
            [tools]
            node = "latest"
            "npm:semantic-release" = "latest"
            "npm:@semantic-release/commit-analyzer" = "latest"
            "npm:@semantic-release/release-notes-generator" = "latest"
            "npm:@semantic-release/github" = "latest"

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
        run: |
          semantic-release \
              ${{ inputs.dry-run && '--dry-run' || '' }} \
              --extends ${{ inputs.config-file }} \
              ${{ inputs.extra-flags }}
