---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Go Test

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        description: The Go version to use.
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Run Tests
        run: go test -v ./... -race -covermode=atomic
