---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - CommitLint

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version"
        required: false
        type: string
        default: "latest"
      commitlint-version:
        description: "Commitlint version"
        required: false
        type: string
        default: "latest"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up Node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: "${{ inputs.node-version }}"

      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install -g @commitlint/cli@${{ inputs.commitlint-version }}

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$PR_TITLE" > file.txt
          commitlint --verbose --color -e=file.txt
