---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - ActionLint

on:
  workflow_call:
    inputs:
      go-version:
        description: "Go version"
        required: false
        type: string
        default: "stable"
      actionlint-version:
        description: "ActionLint version"
        required: false
        type: string
        default: "latest"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@${{ inputs.actionlint-version }}

      - name: Run actionlint
        run: actionlint
