---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - CommitLint

on:
  workflow_call:
    inputs:
      config-file:
        description: "Path to the commitlint config file"
        type: string
        required: false
        default: ".commitlintrc.json"
      extra-flags:
        description: "Additional CLI flags for commitlint"
        type: string
        required: false
        default: "--color --verbose"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    container: docker.io/library/node:23-bookworm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install CommitLint
        run: |
          npm install @commitlint/cli @commitlint/config-conventional
          npm list --depth=0

      - name: Validate PR commits with CommitLint
        if: github.event_name == 'pull_request'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$PR_TITLE" > pr-title.txt
          commitlint --edit=pr-title.txt \
            --config=${{ inputs.config-file }} \
            ${{ inputs.extra-flags }}
