---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - YAMLLint

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        description: The Python version to use.
        required: false
        default: "3.12"
      yamllint-version:
        type: string
        description: The version of yamllint to use.
        required: false
        default: "1.35.1"
      yamllint-args:
        type: string
        description: Additional arguments to pass to yamllint.
        required: false
        default: ""
      working-directory:
        type: string
        description: The directory to lint.
        required: false
        default: "."

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "${{ inputs.python-version }}"

      - name: Install yamllint
        run: pip install yamllint==${{ inputs.yamllint-version }}

      - name: Run yamllint
        run: yamllint ${{ inputs.yamllint-args }} ${{ inputs.working-directory }}
