---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Close Stale Issues

on:
  pull_request:
    paths:
      - ".github/workflows/stale.yaml"

  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@3378cda945da322a8db4b193e19d46352ebe2de5 # v1.10.4
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Close Stale Issues
        uses: actions/stale@v9
        with:
          repo-token: "${{ steps.app-token.outputs.token }}"
          days-before-stale: 60
          days-before-close: 14
          stale-issue-message: "Issue is stale and will be closed in 14 days unless there is new activity"
          stale-pr-message: "PR is stale and will be closed in 14 days unless there is new activity"
          close-issue-message: "Issue is closed due to inactivity"
          close-pr-message: "PR is closed due to inactivity"
          stale-issue-label: "status/stale"
          stale-pr-label: "status/stale"
          exempt-issue-labels: "issue/feature"
          remove-stale-when-updated: "True"
          operations-per-run: 500
          debug-only: "${{ github.event_name == 'pull_request' }}"
